---
title: "loooping"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(ggplot2)
a=0
for (i in 1:5) {
 a = a+i
}
a

# if you want to keep track of a for each iteration
# start with a data structure to hold the results - 
# there will be 5 iterations, so a vector of length 5
# initialize to 0 

av = rep(x=0, times=5)

# now we can fill in the vector with the sum at each iteration
# we can use the counter (i) to access the correct element of the vector
# note that we have to treat the first iteration differently because we don't have a previous value to add to

for (i in 1:5) {
  if (i==1) {
    av[i] = 1
  } else {
  av[i] = av[i-1]+i ##last time i went through the loop 
  }
}
av

testnumbers = runif(min=0, max=20, n=100)
total = 0
nvalues = 100
for (i in 1:nvalues) {
  total = testnumbers[i]+total
}
total/nvalues

mean(testnumbers)
```

```{r}

# lets say we wanted to look at income minus expenses for net income
# create some data for an example

income = runif(min=1000, max=5000, n=10)
income

expenses = rnorm(mean=1500, sd=500, n=10)
expenses

# it is possible that this approach could generate negative expenses
expenses = ifelse(expenses < 0, 0, expenses)

# lets make this a data frame for organization
account = data.frame(income=income, expenses=expenses)
# lets add a year
account$year = seq(from=2000, length.out=nrow(account))

# now compute net income - we could do this with a loop but R is designed to do this without loops
# normally we can just do
account = account %>% mutate(net = income-expenses)
head(account)





```

```{r}
# lets plot
ggplot(account, aes(income, expenses))+geom_point()

```

```{r}
# note that I can use any variable I want as a counter -
# notice how I'm now using n to access each row of the data frame
for (n in 1:10) {
  account$netloop[n] = account$income[n]-account$expenses[n]
}

# as expected net and netloop are the same :)
head(account)


# note: we treat the first year differently because we don't have carry forward
# initialize our column to zero, start counter (n) at 2 instead of 1
# make the first value equal to the net of first year

account$carryforwardnet = 0
account$carryforwardnet[1]=account$net[1]
# now loop - looking backward one year to get previous years carry forward
for (n in 2:10) {
  account$carryforwardnet[n] = account$net[n]+account$carryforwardnet[n-1]
}

# plot - use color to show current year's contribution as positive or negative
ggplot(account, aes(year, carryforwardnet, fill=net, group=year))+geom_col()+
  scale_fill_gradient(low="red", high="black")
```

```{r}
#speed limit 
speedthresh = 120 
#create some sample speeds
speeds = runif(min=0, max = 15, n=300)
nthresh = 0
for ( i in 1:length(speeds)) {
  if(speeds[i] > speedthresh)
     nthresh = nthresh + 1
}

nthresh
# make up sample data
speeds = runif(min = 0, max = 50, n = 300)
# setting a named variable for the threshold makes the code easier to read
hunting_speed = 35
social_speed = 5
num_hunting_speed = 0 
num_social_speed = 0
for (i in 1:length(speeds)) {
  num_hunting_speed = num_hunting_speed + ifelse(speeds[i] >= hunting_speed, 1, 0)
  num_social_speed = num_social_speed + ifelse(speeds[i] < social_speed, 1, 0)
  
}
num_hunting_speed
num_social_speed

# other speeds are traveling, is remainder
num_traveling_speed = length(speeds) - num_hunting_speed - num_social_speed

# as a percent of recorded speeds
num_hunting_speed/length(speeds)*100



```
